# Generated by Django 4.1.7 on 2023-07-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_rename_subject_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(blank=True, null=True)),
                ('Location', models.CharField(blank=True, max_length=300, null=True)),
                ('PhoneNum', models.CharField(blank=True, max_length=300, null=True)),
                ('Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
