# Generated by Django 4.1.7 on 2023-07-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_appointmentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feature', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.CharField(blank=True, choices=[('Photo session', 'Photo session'), ('Drone', 'Drone')], max_length=50, null=True)),
                ('Invoice', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('status', models.CharField(choices=[('partial', 'partial'), ('completed', 'completed'), ('No', 'No'), ('Refunded', 'Refunded')], default='No', max_length=10)),
                ('Basepay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Email', models.EmailField(default='EmailField', max_length=254)),
                ('EmailStatus', models.CharField(choices=[('Partial', 'Partial'), ('Completed', 'Completed'), ('None', 'None')], default='None', max_length=10)),
                ('Date', models.DateField(auto_now_add=True)),
                ('additional_features', models.ManyToManyField(blank=True, to='Base.additionalfeatures')),
            ],
        ),
    ]
