# Generated by Django 4.1.7 on 2023-07-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_additionalfeatures_invoicemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='Description',
        ),
    ]
