# Generated by Django 4.1.7 on 2023-07-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_remove_appointmentrequest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
